apiVersion: batch/v1
kind: Job
metadata:
  name: first-job
spec:
  template:
    spec:
      containers:
        - name: hello
          image: busybox:1.28
          command: ["sh", "-c", 'echo "Hello World!" && sleep 3600']
      restartPolicy: Never